AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  welcome-packet-checklist

  Sample SAM Template for welcome-packet-checklist

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 7
    Runtime: python3.8
    CodeUri: welcome_packet/
Resources:
  PrepareChecklistForDealerfunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: prepare_checklist_for_dealer.lambda_handler
      Events:
        PrepareChecklistForDealer:
          Type: Api
          Properties:
            Path: /checklists/dealer-checklist # append /dealership-name
            Method: get
  GetChecklistByDealerNameFunction: #used by admin to lookup checklist progress for a dealer
    Type: AWS::Serverless::Function
    Properties:
      Handler: get_checklist_by_dealer_name.lambda_handler
      Events:
        GetChecklistByDealeName:
          Type: Api
          Properties:
            Path: /checklists/{dealershipname}
            Method: get
  DealerUpdateChecklistItemsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: update_checklist_item.lambda_handler
      Events:
        UpdateChecklist:
          Type: Api
          Properties:
            Path: /checklists/{dealershipname}
            Method: put
  DealerSubmitChecklistFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: submit_checklist_item.lambda_handler
      Events:
        SubmitChecklist:
          Type: Api
          Properties:
            Path: /checklists/{dealershipname}
            Method: post
#Outputs:
#  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
#  # Find out more about other implicit resources you can reference within SAM
#  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
#  HelloWorldApi:
#    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
#    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
#  HelloWorldFunction:
#    Description: "Hello World Lambda Function ARN"
#    Value: !GetAtt HelloWorldFunction.Arn
#  HelloWorldFunctionIamRole:
#    Description: "Implicit IAM Role created for Hello World function"
#    Value: !GetAtt HelloWorldFunctionRole.Arn
